### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by danielsf** [Starlink/pal#12]
Would it be possible to get a new release that incorporates the changes from https://github.com/Starlink/pal/pull/11 ?

I would like to incorporate that into PALPY and ultimately into the LSST software stack.  LSST policy is to only incorporate tagged releases of third-party packages.

Thanks.

**Comment by timj** [comment]
Tagged as 0.9.4 and github release made. I've made a start at integrating this into palpy in Starlink/palpy#10.
