### ISSUE TITLE
Need an implementation of palDcmpf?

### ISSUE THREAD

**Issue by grahambell** [Starlink/pal#18]
I couldn't find an implementation of palDcmpf.  Is there an alternative, or should I try converting the fortran SLA version to C?

**Comment by timj** [comment]
I only converted what we needed to use. The policy is to first check if a function is in SOFA/ERFA, then if it's not port the code from Fortran SLA to PAL (with the corresponding test from `sla_test.f`).

**Comment by grahambell** [comment]
OK, I've gone ahead and done that.
