### ISSUE TITLE
Remove palEg50 entry from header file

### ISSUE THREAD

**Issue by cxwx** [Starlink/pal#20]

**Comment by timj** [comment]
Can you please be a bit more specific about what you are asking for?

**Comment by cxwx** [comment]
the head file has function
```
void palEg50 ( double dr, double dd, double *dl, double *db );
```
but there is no file has the definition of this function
I think pal is a transplant from slalib, but it loss some file such as palEg50.c

**Comment by timj** [comment]
Thank you for clarifying.  I deliberately included all the slalib functions in the PAL header file so that I could remind myself of all the entries that exist.  I'm not sure why I missed Eg50 implementation.  I will consider a patch that comments out the unimplemented entries.

**Comment by grahambell** [comment]
Pull request #22 was created to do this.
